"""Metrics, temporal cross-validation, and model-card generation."""
from __future__ import annotations

import numpy as np
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    mean_absolute_error,
    precision_score,
    r2_score,
    recall_score,
    roc_auc_score,
)


def classifier_metrics(y_true, proba, threshold=0.5) -> dict:
    pred = (proba >= threshold).astype(int)
    out = {
        "roc_auc": roc_auc_score(y_true, proba),
        "pr_auc": average_precision_score(y_true, proba),
        "f1": f1_score(y_true, pred, zero_division=0),
        "precision": precision_score(y_true, pred, zero_division=0),
        "recall": recall_score(y_true, pred, zero_division=0),
        "accuracy": accuracy_score(y_true, pred),
        "positive_rate": float(np.mean(y_true)),
    }
    return {k: round(float(v), 4) for k, v in out.items()}


def best_threshold(y_true, proba):
    """Pick the decision threshold that maximises F1 on the validation data — a real
    operating point instead of a blind 0.5 cut."""
    grid = np.linspace(0.1, 0.9, 33)
    f1s = [f1_score(y_true, (proba >= t).astype(int), zero_division=0) for t in grid]
    i = int(np.argmax(f1s))
    return float(grid[i]), round(float(f1s[i]), 4)


def regressor_metrics(y_true, pred, baseline=None) -> dict:
    out = {
        "mae": mean_absolute_error(y_true, pred),
        "rmse": float(np.sqrt(np.mean((np.asarray(y_true) - np.asarray(pred)) ** 2))),
        "r2": r2_score(y_true, pred),
    }
    if baseline is not None:
        out["baseline_mae"] = mean_absolute_error(y_true, baseline)
        out["skill_vs_baseline_pct"] = (1 - out["mae"] / out["baseline_mae"]) * 100
    return {k: round(float(v), 4) for k, v in out.items()}


def model_card(task, family, params, metrics, cv, data_report, features, extra="",
               metrics_heading="Hold-out metrics (most recent weeks, never seen in training/CV)",
               selection=None) -> str:
    sel = selection or (f"{cv.get('n_splits','?')}-fold expanding-window time-series CV over "
                        f"{cv.get('n_candidates','?')} candidates")
    lines = [
        f"# Model Card — {task}", "",
        f"**Family:** `{family}`  ", f"**Selected via:** {sel}  ",
        f"**Data:** {data_report['n_cases']:,} FIRs · {data_report['n_districts']} districts · "
        f"{data_report['date_from']} → {data_report['date_to']} · fingerprint `{data_report['data_fingerprint']}`  ",
        "", f"## {metrics_heading}",
    ]
    for k, v in metrics.items():
        lines.append(f"- **{k}**: {v}")
    lines += ["", "## Cross-validation", f"- mean {cv.get('metric','score')}: "
              f"{cv.get('mean'):.4f} ± {cv.get('std'):.4f}" if cv.get("mean") is not None else "- n/a"]
    lines += ["", "## Best hyperparameters", "```json", _fmt(params), "```"]
    lines += ["", "## Features", ", ".join(f"`{f}`" for f in features)]
    if extra:
        lines += ["", extra]
    lines += ["", "_Generated by the KSP crime-forecasting MLOps pipeline._"]
    return "\n".join(lines)


def _fmt(d):
    import json
    return json.dumps(d, indent=2, default=str)
